### PR TITLE
[WIP] Science

### PR DESCRIPTION
**Pull request by yalov**
There are small changes to the "hard" set up that I already have locally based on the original values.
I added as comments stock (or original mods) values.

In the next commit I want 
 * to add comments with the stock values to the stock experiments, 
 * to group EXPERIMENT_DEFINITION by the mods and put "default" and "hard" together. 
This way it will be easier to change or re-balance values. No values will be changes, but it is going to be difficult to check with the diff tool. 
Will you accept that?

### CODE REVIEW

**Comment by yalov** [comment]
oh, you have patches autogenerated by the .xlsx ...

**Comment by hemeac** [comment]
The hard tab was a quick and dirty solution to add a hard difficulty level, but having already had to add some bits for Tantares, can see that maintenance will be a hassle.  I'll take a look at getting an easier solution put together that addresses the balancing for "default" and "hard" without having to cross-reference tabs and have the tables setup with the stock values which it doesn't currently.

**Comment by yalov** [comment]
ok, I will wait, but I still doesn't get, PR suppose to be to the tables or patches?

**Comment by hemeac** [comment]
Not 100% sure.  It could be whatever is easier for you, but I'll take some time this weekend to think if there is an easier way to maintain the science points in the Excel

**Comment by hemeac** [comment]
I've added these values to the 1.3.0 release as I changed a few other things so I will close without accepting the pull request.  It is up to you if you want to make changes in the future to the cfg files or the Excel (latest is https://github.com/hemeac/kiwiTechTree/blob/master/Source/Science_16Dec20.xlsx)

The next release will be a 2.0.0 release as I have written in the forum, so open to suggestions in changes to the default and hard science settings.  Think hard will be the new default as that was really what was intended from the beginning.

**Pull request closed without merging**
